### PR TITLE
Vendor go-bindata

### PR DESCRIPTION
**Pull request by anguslees**
Vendor go-bindata to reduce external dependencies and ensure a
consistent version is used across developers.

### CODE REVIEW

**Comment by anguslees** [comment]
(Is travis-ci working?)

**Comment by mkmik** [comment]
seems broken

**Comment by mkmik** [comment]
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Last successfully run job was June 5th 

https://travis-ci.org/github/bitnami/kubecfg image

**Comment by mkmik** [comment]
I have to ask somebody working at bitnami to fix the config, I no longer have full admin permissions on this repo.

**Comment by mkmik** [comment]
@beltran-rubo thanks!!

**Comment by mkmik** [comment]
@beltran-rubo can you also change the required statuses so that it no longer blocks on `continuous-integration/travis-ci` and instead blocks on whatever is the full name of the one that passes?

**Comment by beltran-rubo** [comment]
I removed that webhook, it should not be an issue for newer PRs

**Comment by mkmik** [comment]
I cannot merge this PR because:


image

**Comment by mkmik** [comment]
Thanks

**Pull request merged**
